version: '3.8'

services:
  autoredeem:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./user_files:/app/user_files
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
